### ISSUE TITLE
Go tools (gopls) stop working via Remote SSH after update to 0.11.5

### ISSUE THREAD

**Issue by halega** [microsoft/vscode-go#2767]
I'm using "Remote - SSH" plugin to work on a Go project. I have Windows host and VirtualBox with Ubuntu VM.

Steps to Reproduce:

1. Open VSCode on Windows, install Remote - SSH plugin and connect to Ubuntu.
2. Do remote install of Go 0.11.5 and install all Go tools (installation completed sucessfully).
3. Open any *.go file.

**Expected**
gopls started on Ubuntu machine and VSCode language features work as expected.

**Actual**
gopls not started and nothing works: no tooltips, no completion, etc.

**Comments**
All works with local projects on Windows.
vscode-go 0.11.4 worked in Remote-SSH.

Version: 1.38.1 (user setup)
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:35:15.005Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362

gopls version
golang.org/x/tools/gopls v0.1.7
    golang.org/x/tools/gopls@v0.1.7 h1:YwKf8t9h69++qCtVmc2q6fVuetFXmmu9LKoPMYLZid4=

golang-vo version 0.11.5

**Comment by halega** [comment]
Reverted remote vscode-go to 0.11.4. All works again.

**Comment by stamblerre** [comment]
Thank you for the issue report. @1yefuwang1 and @enix223, I'll continue the discussion of https://github.com/microsoft/vscode-go/issues/2768 here. Can you add a bit more information about your remote machines?

@ramya-rao-a: Are you aware of any tools for debugging extensions running remotely? My best idea right now is that I can add some more debug logging to my version of the extension, package a new .vsix file, and ask someone to install it remotely and inspect the logs.

**Comment by stamblerre** [comment]
Well, FWIW, I added a few log statements and rebuilt the extension on my fork (https://github.com/stamblerre/vscode-go/blob/master/Go-0.11.5.vsix). If you can download this file onto your remote machine, go to the Extensions menu and click the "..." in the top right corner, you will see the "Install from VSIX" option. If you select Go-0.11.5.vsix file I linked, you'll get the version of the extension with log statements. After reloading the VSCode window, you should see some logs from the extension (you can look at them using "View: Toggle Developer Tools"). If you could share those logs, that might at least help us begin understanding the problem.

**Comment by halega** [comment]
For clean setup I created a VM with Ubuntu Server 18.04.4 in the cloud (any VPS provider is fine). Installed Go and connect to it from VSCode via Remote - SSH from Windows machine. Install remote Go 0.11.5 and gopls.  And it doesn't work. Downgraded to the version 0.11.4 and it start working.

@stamblerre I'll try your build.

**Comment by roblourens** [comment]
You can actually debug a remote extension similarly to how they are debugged locally in the Extension Development Host. Clone the extension to the remote host and open that folder with the Remote-SSH extension. Then the extension debug launch config should work as normal.

**Comment by halega** [comment]
Here's logs.

`10.64.48.17:8080` - it's our corporate HTTP proxy server.

```
 ERR read ECONNRESET: Error: read ECONNRESET
	at TCP.onStreamRead (internal/stream_base_commons.js:111:27)
console.ts:137 [Extension Host] rejected promise not handled within 1 second: Error: connect ETIMEDOUT 10.64.48.17:8080
mainThreadExtensionService.ts:64 [[object Object]]connect ETIMEDOUT 10.64.48.17:8080
mainThreadExtensionService.ts:65 Error: connect ETIMEDOUT 10.64.48.17:8080
	at Request.request [as _callback] (/home/aws/.vscode-server/extensions/ms-vscode.go-0.11.5/node_modules/web-request/index.js:61)
	at self.callback (/home/aws/.vscode-server/extensions/ms-vscode.go-0.11.5/node_modules/request/request.js:185)
	at Request.emit (events.js:182)
	at Request.onRequestError (/home/aws/.vscode-server/extensions/ms-vscode.go-0.11.5/node_modules/request/request.js:881)
	at ClientRequest.emit (events.js:187)
	at onerror (/home/aws/.vscode-server/bin/b37e54c98e1a74ba89e03073e5a3761284e3ffb0/node_modules/agent-base/index.js:100)
	at callbackError (/home/aws/.vscode-server/bin/b37e54c98e1a74ba89e03073e5a3761284e3ffb0/node_modules/agent-base/index.js:122)
	at process._tickCallback (internal/process/next_tick.js:68)
```

On a computer outside corporate network vscode-go 0.11.5 works.

**Comment by halega** [comment]
Figured out that plugin 0.11.5 stop working after updating gopls to v0.1.7. It works with previous version (`version v0.1.6-cmd.gopls, built in $GOPATH mode`). And Go plugin 0.11.5 successfully detect of older version of gopls:

![image](https://user-images.githubusercontent.com/35935/65367912-b76efd00-dc41-11e9-9bc4-5549bd930f46.png)

Steps to reproduce:

1. Remove gopls on remote Linux host.
2. Install Go 0.11.4 and install gopls.
3. Reload VSCode and open remote Go project.
- gopls works
4. Update Go plugin to 0.11.5 and reload VSCode.
- gopls works
- Plugin detects that there's outdated version of gopls and asks to update.
5. Click 'Update'. And reload VSCode.
- gopls stop working
- logs contains errors (see above)

It seems that Go 0.11.5 only doesn't work with gopls v0.1.7 when there's a proxy.

**Comment by stamblerre** [comment]
Are you seeing this behavior with the new beta version of the extension that Ramya pushed (https://github.com/microsoft/vscode-go/releases/tag/latest)? There really shouldn't be anything with `gopls v0.1.7` that would change the behavior of VSCode-Go (it only contained a few minor bug fixes).

**Comment by halega** [comment]
0.11.6-beta.1 also doesn't work.

I see that there're outgoing connections to the corporate proxy from inside VM in VirtualBox:

![image](https://user-images.githubusercontent.com/35935/65368069-061d9680-dc44-11e9-982b-d45029c5d529.png)

When I use VM with Linux as remote machine in the cloud (that is outside of corporate network where there's a proxy), it tries to connect to it anyway: i see the same errors in log:

```
mainThreadExtensionService.ts:65 Error: getaddrinfo ENOTFOUND hqproxy...
```

**Comment by halega** [comment]
No, after some timeout 0.11.6-beta.1 start working:

In logs:
```
Unable to determine latest gopls version: Error: connect ETIMEDOUT 10.64.48.17:8080
```

**Comment by halega** [comment]
Yes, 0.11.6-beta.1 works with gopls v0.1.7. Thanks a lot!

P.S. It's still strage that remote plugin on linux using proxy settings from Windows host. Proxy has domain authentication that's why it fails on linux host in VirtualBox (or in the cloud where there's no proxy at all).

**Comment by kidlj** [comment]
I got this error output in Log(window) with go-extension 0.11.5:

```
[2019-09-21 15:22:42.293] [renderer1] [error] Bad progress location: workbench.view.remote: Error: Bad progress location: workbench.view.remote
    at Proxy.withProgress (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5216:256)
    at $.t.instantiationService.createInstance.e [as withProgress] (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4886:700)
    at $.getChildren (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4892:195)
    at X.<anonymous> (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1026:201)
    at Generator.next (<anonymous>)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:35:566
    at new Promise (<anonymous>)
    at n (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:35:343)
    at a.createCancelablePromise (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1026:138)
    at Object.l [as createCancelablePromise] (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:128:804)
    at X.doGetChildren (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1026:110)
    at X.<anonymous> (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1025:740)
    at Generator.next (<anonymous>)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:35:566
    at new Promise (<anonymous>)
    at n (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:35:343)
    at X.doRefreshNode (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1025:527)
    at X.<anonymous> (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1025:385)
    at Generator.next (<anonymous>)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:35:566
    at new Promise (<anonymous>)
    at n (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:35:343)
    at X.doRefreshSubTree (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1025:316)
    at X.<anonymous> (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1025:163)
    at Generator.next (<anonymous>)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:35:566
    at new Promise (<anonymous>)
    at n (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:35:343)
    at X.refreshNode (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1024:971)
    at X.<anonymous> (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1024:731)
    at Generator.next (<anonymous>)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:35:566
    at new Promise (<anonymous>)
    at n (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:35:343)
    at X.refreshAndRenderNode (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1024:684)
    at X.<anonymous> (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1022:62)
    at Generator.next (<anonymous>)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:35:566
    at new Promise (<anonymous>)
    at n (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:35:343)
    at X.updateChildren (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1021:821)
    at Promise.all.Array.from.map.e (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4891:237)
    at Array.map (<anonymous>)
    at K.<anonymous> (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4891:228)
    at Generator.next (<anonymous>)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:35:566
    at new Promise (<anonymous>)
    at n (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:35:343)
    at K.doRefresh (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4891:8)
    at K._register.themeService.onDidFileIconThemeChange (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4883:666)
    at d.fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:107:468)
    at V.doSetFileIconTheme (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4622:717)
    at e (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4621:711)
    at R (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4611:724)
    at i.ensureLoaded.then.e (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4621:698)
```

**Comment by kidlj** [comment]
From Developer Tools view I got this. I seems to connect to an internet address to determine something, please don't do this, almost every google/github/aws/azure servers are blocked in China. 

<img width="898" alt="image" src="https://user-images.githubusercontent.com/300616/65369798-6e8c6800-dc84-11e9-969a-8c59630b0148.png">

**Comment by ramya-rao-a** [comment]
Thanks @halega & @kidlj 

@kidlj For the time being, can try the [latest beta version](https://github.com/microsoft/vscode-go/wiki/Use-the-beta-version-of-the-latest-Go-extension)? It has the fix to not block the starting of the language server when failing to connect to the proxy.

**Comment by ramya-rao-a** [comment]
Hello all,

I have just released an update where we have replaced the outgoing call with known hard-coded value of the latest version for gopls. This should fix the problem reported here.

I have logged an issue #2776 to discuss next steps on how to make this check better, please feel free to provide your thoughts there.
