### ISSUE TITLE
Extension doesn't seem to start.

### ISSUE THREAD

**Issue by ripbandit** [Microsoft/vscode-go#1527]
Here's the code I was trying to use the extension with: 
``` Go
package main

import (
	"net/http"
	"github.com/go-chi/chi"
)

func newRouter() *chi.Mux {
	r := chi.NewRouter()
	r.Get("/", func (w http.ResponseWriter, r *http.Request) {
		w.Write([]byte("HELLO"))
	})
	return r
}

func main() {
	r := newRouter()
	http.ListenAndServe(":1337", r)
}
```
The only things I've changed recently are updating Go to 1.10 and updating VSCode to 1.20.1. Running `gocode close` and `gocode -s -debug` produces nothing. I'm on Windows 10 if that helps at all!

**Comment by kharism** [comment]
I happened to me too, at developer console I found
error stack:  Error: Cannot find module 'applicationinsights'
	at Function.Module._resolveFilename (module.js:470:15)
	at Function.Module._load (module.js:418:25)
	at Function.o._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:664:413)
	at Module.require (module.js:498:17)
	at require (internal/module.js:20:19)
	at Object.<anonymous> (C:\Users\User\.vscode\extensions\lukehoban.go-0.6.76\node_modules\vscode-extension-telemetry\lib\telemetryReporter.js:18:19)
	at Object.<anonymous> (C:\Users\User\.vscode\extensions\lukehoban.go-0.6.76\node_modules\vscode-extension-telemetry\lib\telemetryReporter.js:106:3)
	at Module._compile (module.js:571:32)
	at Object.Module._extensions..js (module.js:580:10)
	at Module.load (module.js:488:32)

**Comment by ramya-rao-a** [comment]
@ripbandit Any errors in the console? Help -> Toggle Developer Tools -> Console.

@kharism Try uninstalling the extension and installing it back

**Comment by ljubomirb** [comment]
> mine also does not work after I updated to 1.20.1

I've tested this with vscode 1.20.1 and vscode-go 0.6.76. It works.
However, I am running this on `go version go1.8.3 linux/amd64`
I'm close to believe (although not sure) this has all started with Go 1.10 having some part of API a bit different. Maybe that "vet" change?

**Comment by ripbandit** [comment]
@ramya-rao-a Here's the error I get in the console:
```
[Extension Host] Here is the error stack:  Error: Cannot find module 'vscode-extension-telemetry'
	at Function.Module._resolveFilename (module.js:470:15)
	at Function.Module._load (module.js:418:25)
	at Function.o._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:664:413)
	at Module.require (module.js:498:17)
	at require (internal/module.js:20:19)
	at Object.<anonymous> (C:\Users\ripba\.vscode\extensions\lukehoban.go-0.6.76\out\src\util.js:11:38)
	at Object.<anonymous> (C:\Users\ripba\.vscode\extensions\lukehoban.go-0.6.76\out\src\util.js:707:3)
	at Module._compile (module.js:571:32)
	at Object.Module._extensions..js (module.js:580:10)
	at Module.load (module.js:488:32)
	at tryModuleLoad (module.js:447:12)
	at Function.Module._load (module.js:439:3)
	at Function.o._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:664:413)
	at Module.require (module.js:498:17)
	at require (internal/module.js:20:19)
	at Object.<anonymous> (C:\Users\ripba\.vscode\extensions\lukehoban.go-0.6.76\out\src\goSuggest.js:9:16)
```

**Comment by ramya-rao-a** [comment]
@ljubomirb The stack trace that @kharism shared is about the missing module `application insights`. Its not related Go 1.10

@kharism @ripbandit Somehow the extension is stuck in a bad state with missing modules. Can you uninstall the extension -> reload -> install it again?

**Comment by ripbandit** [comment]
@ramya-rao-a I just tried that, still have the same error as above.

**Comment by ramya-rao-a** [comment]
@ripbandit Delete the `lukehoban.go-0.6.76` folder under `C:\Users\ripba\.vscode\extensions` and try again

**Comment by ripbandit** [comment]
@ramya-rao-a That seems to have solved the issue!

**Comment by kharism** [comment]
that works for me also, thanks
