### ISSUE TITLE
Support the Run action by using the noDebug launch arg

### ISSUE THREAD

**Issue by MrLiet** [Microsoft/vscode-go#618]
Hello.

I have compile error:

![image](https://cloud.githubusercontent.com/assets/23429917/20272702/4ff18ac6-aac1-11e6-9e7b-215ac472d93c.png)

Source code:

```
package main

import "github.com/go-gl/glfw/v3.2/glfw"
import "runtime"

func main() {

	runtime.LockOSThread()

	glfw.Init()

	w, _ := glfw.CreateWindow(800, 600, "hello", nil, nil)

	for {
		glfw.PollEvents()
		if w.ShouldClose() {
			break
		}
	}

}
```

Console output:

> me/proj1
> github.com/go-gl/glfw/v3.2/glfw(.text): strdup: not defined
> github.com/go-gl/glfw/v3.2/glfw(.text): strdup: not defined
> github.com/go-gl/glfw/v3.2/glfw(.text): strdup: not defined
> github.com/go-gl/glfw/v3.2/glfw(.text): strdup: not defined
> github.com/go-gl/glfw/v3.2/glfw(.text): undefined: strdup
> github.com/go-gl/glfw/v3.2/glfw(.text): undefined: strdup
> github.com/go-gl/glfw/v3.2/glfw(.text): undefined: strdup
> github.com/go-gl/glfw/v3.2/glfw(.text): undefined: strdup
> exit status 2
> 

Im use:

- Windows 64 bit
- Go 1.7.3 
- Mingw 64
- VS Code

VS Code settings:
```
{
    "go.buildOnSave": true,
    "go.lintOnSave": true,
    "go.vetOnSave": true,
    "go.buildTags": "",
    "go.buildFlags": [],
    "go.lintTool": "golint",
    "go.lintFlags": [],
    "go.vetFlags": [],
    "go.coverOnSave":false,
    "go.useCodeSnippetsOnFunctionSuggest": true,
    "go.formatOnSave": true, 
    "go.formatTool": "goreturns",
    "go.formatFlags": [],
    "go.gocodeAutoBuild": false,
    "go.autocompleteUnimportedPackages": true
}
```

and Launch settings:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch",
            "type": "go",
            "request": "launch",
            "mode": "debug",
            "program": "${workspaceRoot}",
            "env": {},
            "args": []
        }
    ]
}
```

And it's work fine with glfw 3.1 version
![image](https://cloud.githubusercontent.com/assets/23429917/20272758/7aef4be6-aac1-11e6-8d41-a8a5081817a6.png)

GLFW supports says: 

> You're probably using an old version of Go.

Delve supports says:

> Dlv itself just uses whatever go happens to be in the path. The VSCode plugin is maintained here.

Help!

**Comment by MrLiet** [comment]
Im know its Delve bug.

Question: Can i run code without delve debugger inside VS Code ?

**Comment by ramya-rao-a** [comment]
> Question: Can i run code without delve debugger inside VS Code ?

Without using delve debugger, you can only run the `go` commands in the integrated terminal. Like `go build` `go run` etc.

@roblourens Can you help with the debugging aspect of the issue?

**Comment by roblourens** [comment]
It sounds like you just want to run code (without debugging it) from vscode, to avoid using Delve?

There's no way to do that now, without starting it from the terminal. node-debug does have that option though, through the launch config option `noDebug`, and maybe we could add it to go-debug too.

**Comment by ramya-rao-a** [comment]
https://github.com/Microsoft/vscode/issues/2780

**Comment by ramya-rao-a** [comment]
Closing as duplicate of #299 
Will track the work there to support the "Run action" as described https://github.com/Microsoft/vscode/issues/2780

**Comment by ramya-rao-a** [comment]
In the latest update (0.6.56), you can 
        - Press `Ctrl+F5` or run the command `Debug: Start Without Debugging` to run using the currently selected launch configuration.
        - If you don't have a `launch.json` file, then the current file will be run.
        - Supported only for launch configs with `type` as `debug` and `program` that points to a Go file and not package
