### ISSUE TITLE
tests don't run anymore after updating to vscode 1.26.0

### ISSUE THREAD

**Issue by pierrre** [Microsoft/vscode-go#1844]
Steps to Reproduce:

1. upgrade to vscode 1.26.0
2. run Go tests, nothing happens

"automatic test on save" doesn't work anymore too.

With vscode 1.25 it works.

**Comment by benweissmann** [comment]
I'm also seeing this intermittently after upgrading to 1.26.0. Sometimes, the "run test"/"debug test" buttons disappear, and the "Go: Run tests" action stops working. Restarting sometimes helps, but the issue comes back after a few minutes.

**Comment by ramya-rao-a** [comment]
- @pierrre, @benweissmann   Do you see any errors in the console? Help -> Toggle Developer Tools -> Console ?
- @benweissmann Do you also see this working as expected in 1.25?

**Comment by nboughton** [comment]
Build on save functionality is completely broken for me in 1.26. Every time I save I get the following in the console:

``mainThreadExtensionService.ts:43 [ms-vscode.Go]ENOENT: no such file or directory, uv_os_get_passwd
e.$onExtensionRuntimeError @ mainThreadExtensionService.ts:43
e._doInvokeHandler @ rpcProtocol.ts:261
e._invokeHandler @ rpcProtocol.ts:246
e._receiveRequest @ rpcProtocol.ts:192
e._receiveOneMessage @ rpcProtocol.ts:174
(anonymous) @ rpcProtocol.ts:107
(anonymous) @ rpcProtocol.ts:303
e.fire @ event.ts:140
a @ ipc.net.ts:104
n._socketDataListener @ ipc.net.ts:133
emitOne @ events.js:116
emit @ events.js:211
addChunk @ _stream_readable.js:263
readableAddChunk @ _stream_readable.js:250
Readable.push @ _stream_readable.js:208
onread @ net.js:594
mainThreadExtensionService.ts:44 Error: ENOENT: no such file or directory, uv_os_get_passwd
	at Object.goBuild (/home/nick/.vscode/extensions/ms-vscode.go-0.6.87/out/src/goBuild.js:71:102)
	at Object.check (/home/nick/.vscode/extensions/ms-vscode.go-0.6.87/out/src/goCheck.js:75:45)
	at runBuilds (/home/nick/.vscode/extensions/ms-vscode.go-0.6.87/out/src/goMain.js:334:15)
	at vscode.workspace.onDidSaveTextDocument.document (/home/nick/.vscode/extensions/ms-vscode.go-0.6.87/out/src/goMain.js:347:9)
	at e.fire (/opt/visual-studio-code/resources/app/out/vs/workbench/node/extensionHostProcess.js:98:218)
	at e.$acceptModelSaved (/opt/visual-studio-code/resources/app/out/vs/workbench/node/extensionHostProcess.js:728:141)
	at e._doInvokeHandler (/opt/visual-studio-code/resources/app/out/vs/workbench/node/extensionHostProcess.js:671:983)
	at e._invokeHandler (/opt/visual-studio-code/resources/app/out/vs/workbench/node/extensionHostProcess.js:671:701)
	at e._receiveRequest (/opt/visual-studio-code/resources/app/out/vs/workbench/node/extensionHostProcess.js:670:767)
	at e._receiveOneMessage (/opt/visual-studio-code/resources/app/out/vs/workbench/node/extensionHostProcess.js:670:536)
	at /opt/visual-studio-code/resources/app/out/vs/workbench/node/extensionHostProcess.js:669:452
	at /opt/visual-studio-code/resources/app/out/vs/workbench/node/extensionHostProcess.js:672:575
	at /opt/visual-studio-code/resources/app/out/vs/workbench/node/extensionHostProcess.js:96:903
	at e.fire (/opt/visual-studio-code/resources/app/out/vs/workbench/node/extensionHostProcess.js:98:218)
	at a (/opt/visual-studio-code/resources/app/out/vs/workbench/node/extensionHostProcess.js:162:713)
	at Socket._socketDataListener (/opt/visual-studio-code/resources/app/out/vs/workbench/node/extensionHostProcess.js:162:932)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at Pipe.onread (net.js:594:20)

Attempting to use the command pallet to build the current workspace also fails with the following error:

`

  | t.onDidNotificationChange | @ | notificationsAlerts.ts:39
-- | -- | -- | --
  | (anonymous) | @ | notificationsAlerts.ts:27
  | e.fire | @ | event.ts:140
  | t.notify | @ | notifications.ts:113
  | t.error | @ | notificationService.ts:52
  | t.onError | @ | commandsHandler.ts:325
  | (anonymous) | @ | commandsHandler.ts:310
  | done | @ | winjs.base.js:1399
  | v | @ | winjs.base.js:1245
  | enter | @ | winjs.base.js:916
  | _run | @ | winjs.base.js:1089
  | _error | @ | winjs.base.js:1062
  | e.resolveErr | @ | lazyPromise.ts:78
  | e._receiveReplyErr | @ | rpcProtocol.ts:241
  | e._receiveOneMessage | @ | rpcProtocol.ts:183
  | (anonymous) | @ | rpcProtocol.ts:107
  | (anonymous) | @ | rpcProtocol.ts:303
  | e.fire | @ | event.ts:140
  | a | @ | ipc.net.ts:104
  | n._socketDataListener | @ | ipc.net.ts:133
  | emitOne | @ | events.js:116
  | emit | @ | events.js:211
  | addChunk | @ | _stream_readable.js:263
  | readableAddChunk | @ | _stream_readable.js:250
  | Readable.push | @ | _stream_readable.js:208
  | onread | @ | net.js:594

`

**Comment by ramya-rao-a** [comment]
@nboughton Please uninstall the current version of VS Code and install the older version from https://code.visualstudio.com/updates/v1_25 to figure out if the problem is due to the new version of VS Code or the new version of the Go extension

**Comment by pierrre** [comment]
I see the same error message in the developer console.

When I try to run the tests manually, it displays a popup:
> No tests found. Current file is not a test file.

(even if I've got a test file)

I confirm that a downgrade to 1.25 fixes the issue.

**Comment by ramya-rao-a** [comment]
@pierrre 

> I see the same error message in the developer console.

Do you mean the error about `uv_os_get_passwd`. If yes, then please follow https://github.com/Microsoft/vscode-go/issues/1850#issuecomment-413219344 to get the fix for that

> No tests found. Current file is not a test file.

For `Go: Test File` or `Go: Test Function At Cursor`, a test file should be open in the active editor. Can you open a test file and click on one of the "run test" codelens?

**Comment by pierrre** [comment]
> Do you mean the error about uv_os_get_passwd. If yes, then please follow #1850 (comment) to get the fix for that

Yes, #1850 fix is working for me, thanks !

> For Go: Test File or Go: Test Function At Cursor, a test file should be open in the active editor. Can you open a test file and click on one of the "run test" codelens?

This bug is also solved with #1850 fix

**Comment by ramya-rao-a** [comment]
That's good to know, thanks!
